### ISSUE TITLE
Failed to load library 'cisco_node_utils' for feature 'cisco_node_utils' 

### ISSUE THREAD

**Issue by ademariag** [cisco/cisco-network-node-utils#603]
Hello,

I am trying to setup puppet to use the https://forge.puppet.com/puppetlabs/ciscopuppet puppet module.

however, I run in the following problems:
```
Debug: Failed to load library 'cisco_node_utils' for feature 'cisco_node_utils'
Debug: /Package[cisco_node_utils]: Provider gem does not support features virtual_packages; not managing attribute allow_virtual
Debug: Failed to load library 'cisco_node_utils' for feature 'cisco_node_utils'
Debug: Puppet::Type::Cisco_vlan::ProviderCisco: feature cisco_node_utils is missing
Debug: Failed to load library 'cisco_node_utils' for feature 'cisco_node_utils'
Debug: Puppet::Type::Cisco_vlan::ProviderCisco: feature cisco_node_utils is missing
Error: Could not find a suitable provider for cisco_vlan 
```

## on the client side:
```
puppet agent --version
4.10.12
```
### I have the following gems
```
gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (default: 1.16.6)
cisco_node_utils (1.10.0)
io-console (0.4.2)
json (1.7.7)
net_http_unix (0.2.2)
psych (2.0.0)
rake (12.3.2)
rdoc (4.0.0)
rubygems-update (2.7.8)
```

## On the `puppetserver` side 
```
puppetserver --version
puppetserver version: 5.3.6
```

### I am unable to install the `cisco_node_utils` gem:

```
puppetserver gem install cisco_node_utils
Building native extensions.  This could take a while...
ERROR:  Error installing cisco_node_utils:
        ERROR: Failed to build gem native extension.

    current directory: /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/cisco_node_utils-1.10.0/ext
/usr/lib/jvm/java-8-oracle/jre/bin/java -cp :/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar:/opt/puppetlabs/server/apps/puppetserver/jruby-9k.jar:/opt/puppetlabs/server/data/puppetserver/jars/* org.jruby.Main mkrf_conf.rb
Found installed gems matching net_http_unix (>= 0.2.1, ~> 0.2):
  net_http_unix (0.2.2)
Installing grpc (~> 1.14.1)
Building native extensions.  This could take a while...
ERROR: Failed to build gem native extension.

    current directory: /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/google-protobuf-3.6.1/ext/google/protobuf_c
/usr/lib/jvm/java-8-oracle/jre/bin/java -cp :/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/cisco_node_utils-1.10.0/ext:/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar:/opt/puppetlabs/server/apps/puppetserver/jruby-9k.jar:/opt/puppetlabs/server/data/puppetserver/jars/* org.jruby.Main -r ./siteconf20181215-13075-zk3mkp.rb extconf.rb
creating Makefile

current directory: /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/google-protobuf-3.6.1/ext/google/protobuf_c
make "DESTDIR=" clean
Makefile:225: *** multiple target patterns.  Stop.

current directory: /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/google-protobuf-3.6.1/ext/google/protobuf_c
make "DESTDIR="
Makefile:225: *** multiple target patterns.  Stop.

make failed, exit code 2

Gem files will remain installed in /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/google-protobuf-3.6.1 for inspection.
Results logged to /opt/puppetlabs/server/data/puppetserver/jruby-gems/extensions/universal-java-1.8/2.3.0/google-protobuf-3.6.1/gem_make.out
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:92:in `run'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:52:in `block in make'
  org/jruby/RubyArray.java:1735:in `each'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:44:in `make'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  org/jruby/RubyIO.java:1171:in `open'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/ext_conf_builder.rb:31:in `build'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:164:in `block in build_extension'
  org/jruby/RubyDir.java:323:in `chdir'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:163:in `block in build_extension'
  org/jruby/ext/thread/Mutex.java:158:in `synchronize'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:162:in `build_extension'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:201:in `block in build_extensions'
  org/jruby/RubyArray.java:1735:in `each'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:198:in `build_extensions'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/installer.rb:764:in `build_extensions'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/installer.rb:304:in `install'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/resolver/specification.rb:97:in `install'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/request_set.rb:166:in `block in install'
  org/jruby/RubyArray.java:1735:in `each'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/request_set.rb:156:in `install'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/dependency_installer.rb:405:in `install'
  mkrf_conf.rb:46:in `block in mkrf_conf.rb'
  org/jruby/RubyArray.java:1735:in `each'
  mkrf_conf.rb:42:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/cisco_node_utils-1.10.0 for inspection.
Results logged to /opt/puppetlabs/server/data/puppetserver/jruby-gems/extensions/universal-java-1.8/2.3.0/cisco_node_utils-1.10.0/gem_make.out
```

This seems to be a problem with installing `google-protocolbuf` on jruby (see [this bug](https://github.com/protocolbuffers/protobuf/issues/1594))

Can you help me understand how to fix this issue?

**Comment by ademariag** [comment]
One possible problem is that I believe the gem should be installed with the following command
```/opt/puppetlabs/puppet/bin/gem install cisco_node_utils
Building native extensions.  This could take a while...
sh: line 1: 19467 Killed                  /opt/puppetlabs/puppet/bin/ruby mkrf_conf.rb 2>&1
ERROR:  Error installing cisco_node_utils:
        ERROR: Failed to build gem native extension.

    /opt/puppetlabs/puppet/bin/ruby mkrf_conf.rb

rake failed, exit code 137

Gem files will remain installed in /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cisco_node_utils-1.10.0 for inspection.
Results logged to /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/cisco_node_utils-1.10.0/gem_make.out
```

**Comment by mikewiebe** [comment]
@ademariag Is there a specific reason you are installing the gem on your puppet server?  The gem is typically installed on your agent (Nexus) device and provides the objects needed for puppet to manage the NX-OS features.

**Comment by ademariag** [comment]
Hi no reason other than the fact that it was not working by just installing it in the client. In fact I wanted to get a confirmation from you that only the client was needed.

However, installing it in the client on the system `gem` does not work, and using `/opt/puppetlabs/puppet/bin/gem` produce the error above. What is the correct way to install it?

The failure is possible due to the cloudshell running out of space or memory. Do you have a recommended size?

**Comment by mikewiebe** [comment]
@ademariag What type of NX-OS device and software version are you running as the puppet agent?

**Comment by ademariag** [comment]
NX-OS 9.2
The Switch model is Cisco Nexus9000 C93180LC-EX Chassis

Puppet version 4.x, happy to upgrade it to 5.3

**Comment by mikewiebe** [comment]
@ademariag Are you attempting to install the gem in the `Guestshell` or `Bash Shell` on the N9k?

**Comment by ademariag** [comment]
Guestshell

**Comment by mikewiebe** [comment]
@ademariag I just setup my N9k to run software version 9.2.  I am not seeing any issues installing the gem.  Here is my workflow.

This assumes you have already installed puppet.  My version.

```shell
[root@guestshell ~]# puppet --version
4.10.12
[root@guestshell ~]# 
```


```shell
n9k# guestshell 
[admin@guestshell ~]$ sudo su -
Last login: Mon Dec 17 19:36:54 UTC 2018 on pts/4
[root@guestshell ~]# chvrf management
[root@guestshell ~]# export PATH=/opt/puppetlabs/puppet/bin:/opt/puppetlabs/puppet/lib:$PATH
[root@guestshell ~]# export http_proxy=http://proxy.example.com:80
[root@guestshell ~]# export https_proxy=https://proxy.example.com:80
[root@guestshell ~]# gem list | grep cisco
[root@guestshell ~]# 
[root@guestshell ~]# gem install cisco_node_utils
Fetching: cisco_node_utils-1.10.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed cisco_node_utils-1.10.0
Parsing documentation for cisco_node_utils-1.10.0
Installing ri documentation for cisco_node_utils-1.10.0
Done installing documentation for cisco_node_utils after 12 seconds
1 gem installed
[root@guestshell ~]#
```

NOTE: The proxy setting is optional and only needed if you are in a lab that needs it to get access to rubygems.org.

**Comment by ademariag** [comment]
```
[root@V-Nexus9K-01 ~]# puppet --version
4.10.12
```

```
[root@V-Nexus9K-01 ~]# sudo chvrf management
[root@V-Nexus9K-01 ~]# export PATH=/opt/puppetlabs/puppet/bin:/opt/puppetlabs/puppet/lib:$PATH
[root@V-Nexus9K-01 ~]# gem list | grep cisco
[root@V-Nexus9K-01 ~]# gem install cisco_node_utils
Building native extensions. This could take a while...
Successfully installed cisco_node_utils-1.10.0
Parsing documentation for cisco_node_utils-1.10.0
Installing ri documentation for cisco_node_utils-1.10.0
Done installing documentation for cisco_node_utils after 8 seconds
1 gem installed
[root@V-Nexus9K-01 ~]# gem list | grep cisco
cisco_node_utils (1.10.0)
[root@V-Nexus9K-01 ~]# puppet agent -t --environment cisco        
Info: Using configured environment 'cisco'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for v-nexus9k-01XXXX
Info: Applying configuration version '1545085324'
Notice: Applied catalog in 0.29 seconds
```

I have no idea why it wasn't working previously. Thank you. Will reset and try again just to make sure there wasn't something else wrong
